### ISSUE TITLE
Neither rbx-xml nor rbx-binary properly add children

### ISSUE THREAD

**Issue by Kampfkarren** [LPGhatguy/rbx-tree#1]
I'm not sure if I'm using it wrong, but rbx-xml doesn't seem to add anything other than the initial root node you create. Here was the code I was using:

```
lazy_static! {
    #[rustfmt::skip]
    static ref HATS_TREE: RbxTree = {
        let mut tree = RbxTree::new(RbxInstance {
            name: "Hats".to_string(),
            class_name: "Hats".to_string(),
            properties: HashMap::new(),
        });

        let root_id = tree.get_root_id();

        rbx_xml::decode(
            &mut tree,
            root_id,
            fs::File::open("./test/roblox.rbxmx").expect("Couldn't read roblox.rbxmx"),
        ).expect("rbxmx failed to parse");

        tree
    };
}
```

Followed by:

`println!("{:?}", HATS_TREE.descendants(HATS_TREE.get_root_id()).collect::<Vec<_>>()); `

When this is used, it only shows the root node and no descendants.
`[RootedRbxInstance { instance: RbxInstance { name: "Hats", class_name: "Hats", properties: {} }, id: RbxId(Uuid([15, 19, 159, 200, 130, 135, 75, 151, 140, 168, 23, 144, 220, 6, 153, 57])), children: [], parent: None }]`

rbx-binary on the other hand shows everything as expected.

[roblox.zip](https://github.com/LPGhatguy/rbx-tree/files/2686747/roblox.zip)

**Comment by Kampfkarren** [comment]
Scratch this: rbx-binary prints out everything but neither `descendants` nor `get_children_ids` return anything other than empty lists.

**Comment by Kampfkarren** [comment]
https://github.com/LPGhatguy/rbx-tree/blob/1719d35df9b08637c2938d4418e834e48f39f624/rbx_binary/src/deserializer.rs#L80

rbx-binary prints out everything, but doesn't actually add it to the instance?

**Comment by Kampfkarren** [comment]
Rojo doesn't use decode at any point so that might explain why these don't actually work.

**Comment by LPGhatguy** [comment]
Fixed!
